---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  always_update_cookbooks: false
  roles_path: ../../roles
  data_bags_path: ../../data_bags
  encrypted_data_bag_secret_key_path: "../../secret_key"

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - role[tracks]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      authorization:
        sudo:
          users: ['kitchen', 'vagrant']
          passwordless: true
          include_sudoers_d: true
