---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  always_update_cookbooks: false
  client_rb:
    audit_mode: :audit_only

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[audit-cis::ubuntu1404-100]
      - recipe[medi-audit-cis::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
